spring:
  application:
    name: bookshop
  jpa:
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  servlet:
    context-path: /api
jwt:
  expiration: 300000
  secret: secretKeysf9yh329rjfdfdds7fgertfsdg5454ggvv45v45g4g545gv45v45vv45v54v54dxsd
